import React from "react";
import { StarPlus } from "lucide-react";
import "./Features.css";
import { ChevronRight } from "lucide-react";
import AI_poweredImg from "../assets/Chatbot.png";
import ATS_scoreImg from "../assets/ATS_score.png";
import downloadImg from "../assets/download.png";
import smartAnalytics from "../assets/smart analytics.png";
import Templates from "../assets/templates.png";
import secure from "../assets/secure.png";
import { useNavigate } from "react-router-dom";

const Features = () => {
  const navigate = useNavigate();
  return (
    <>
      <div className="container">
        <div className="header-text">
          <span>
            <StarPlus size={16} />
            POWERFUL FEATURES
          </span>
        </div>
        <div className="header-title">
          <h1>
            Everything You Need to Build the{" "}
            <span style={{ color: "rgb(124, 58, 237)" }}>Perfect </span> Resume
          </h1>

          <p>
            Advanced tools and intelligent features to help you create resumes
            that get you hired.
          </p>
        </div>
        <div className="content-container">
          <div className="content">
            <div className="img">
              <img src={AI_poweredImg} alt="AI powered content" />
              <span>
                <ChevronRight onClick={() => navigate("/login")} />
              </span>
            </div>
            <div className="content-text">
              <h1>Al-Powered Content</h1>
              <p>
                Get personalized content suggestions, bullet points, and
                summaries generated by advanced Al,
              </p>
            </div>
          </div>
          <div className="content">
            <div className="img">
              <img src={ATS_scoreImg} alt="ATS score checker" />
              <span>
                <ChevronRight onClick={() => navigate("/login")} />
              </span>
            </div>
            <div className="content-text">
              <h1>ATS Score Checker</h1>
              <p>
                Analyze your resume against ATS systems and get actionable
                suggestions to improve your score.
              </p>
            </div>
          </div>
          <div className="content">
            <div className="img">
              <img src={Templates} alt="Templates" />
              <span>
                <ChevronRight onClick={() => navigate("/login")} />
              </span>
            </div>
            <div className="content-text">
              <h1>Professional Templates</h1>
              <p>
                Choose from 20+ ATS-friendly templates designed by HR experts
                and industry professionals.
              </p>
            </div>
          </div>
          <div className="content">
            <div className="img">
              <img src={downloadImg} alt="easy download" />
              <span>
                <ChevronRight onClick={() => navigate("/login")} />
              </span>
            </div>
            <div className="content-text">
              <h1>Easy Download</h1>
              <p>
                Download your resume in multiple formats including PDF, DOCX,
                and TXT with one click.
              </p>
            </div>
          </div>
          <div className="content">
            <div className="img">
              <img src={smartAnalytics} alt="smart analytics" />
              <span>
                <ChevronRight onClick={() => navigate("/login")} />
              </span>
            </div>
            <div className="content-text">
              <h1>Smart Analytics</h1>
              <p>
                Track views, downloads, and engagement to understand your resume
                performance.
              </p>
            </div>
          </div>
          <div className="content">
            <div className="img">
              <img src={secure} alt="secure & pro" />
              <span>
                <ChevronRight onClick={() => navigate("/login")} />
              </span>
            </div>
            <div className="content-text">
              <h1>Secure & Private</h1>
              <p>
                Your data is encrypted and stored securely. We never share your
                information with third parties.
              </p>
            </div>
          </div>
        </div>
      </div>
    </>
  );
};

export default Features;
